if ( 'prettyPrint' in window ) {} else {
    document.write( '<script type="text/javascript" src="https://gist-it.appspot.com/assets/prettify/prettify.js"></script>' );
}


document.write( '<link rel="stylesheet" href="https://gist-it.appspot.com/assets/embed.css"/>' );


document.write( '<link rel="stylesheet" href="https://gist-it.appspot.com/assets/prettify/prettify.css"/>' );

document.write( '<div class="gist-it-gist">\n<div class="gist-file">\n    <div class="gist-data">\n        \n        <pre class="prettyprint">/*********\n  Rui Santos\n  Complete project details at http://randomnerdtutorials.com  \n*********/\n\nint pin = 2;\n\nvoid setup() {\n  // initialize GPIO 2 as an output.\n  pinMode(pin, OUTPUT);\n}\n\n// the loop function runs over and over again forever\nvoid loop() {\n  digitalWrite(pin, HIGH);   // turn the LED on (HIGH is the voltage level)\n  delay(1000);               // wait for a second\n  digitalWrite(pin, LOW);    // turn the LED off by making the voltage LOW\n  delay(1000);               // wait for a second\n}\n</pre>\n        \n    </div>\n    \n    <div class="gist-meta">\n        \n        <span style="float: right; color: #369;"><a href="https://github.com/RuiSantosdotme/Random-Nerd-Tutorials/raw/master/Projects/blink_led_esp8266.ino">view raw</a></span>\n        <span style="float: right; margin-right: 8px;">\n            <a style="color: rgb(102, 102, 102);" href="https://github.com/RuiSantosdotme/Random-Nerd-Tutorials/blob/master/Projects/blink_led_esp8266.ino">Projects/blink_led_esp8266.ino</a></span>\n            <!-- Generated by: https://gist-it.appspot.com -->\n    </div>\n    \n</div>\n</div>' );

document.write( '<script type="text/javascript">prettyPrint();</script>' );